language: objective-c
xcode_workspace: Example/GeoFeatures.xcworkspace
xcode_scheme: GeoFeatures-Example
osx_image: xcode7.1

before_install:
    - brew install xctool
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:
  - xctool -workspace Example/GeoFeatures-iOS.xcworkspace -scheme GeoFeatures-iOS-Example -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test
  - xctool -workspace Example/GeoFeatures-OSX.xcworkspace -scheme GeoFeatures-OSX-Example -sdk macosx          GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test

after_success:
  - bash <(curl -s https://codecov.io/bash)
