language: objective-c
xcode_workspace: Example/GeoFeatures.xcworkspace
xcode_scheme: GeoFeatures-Example
osx_image: xcode6.4
xcode_sdk: iphonesimulator8.4

Script:
  xctool -workspace Example/GeoFeatures.xcworkspace -scheme GeoFeatures-Example clean build test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
