comment:
  layout: header, changes, diff, sunburst
coverage:
  ignore:
  - Applications/.*
  - Example/.*
  - GeoFeatures/boost/.*
  - GeoFeatures/internal/.*
  - GeoFeatures/Internal/.*
  status:
    patch: false
    project: false
    
